import { SEMANTIC_PART_REGISTRY } from './part-registry.js';
import { findSemanticPartByElement } from './part-model.js';
import { createSemanticRigCommands } from './semantic-rig-commands.js';
import { createArtworkCommands } from '../../core/commands/artwork-commands.js';

const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const words=value=>({lookX:'Look left / right',lookY:'Look up / down',eyeOpen:'Open / close',mouthOpen:'Open / close',headX:'Move left / right',headY:'Move up / down',headTilt:'Tilt',scaleY:'Squash vertically',scaleX:'Stretch horizontally',translateX:'Move horizontally',translateY:'Move vertically',rotation:'Rotate',morph:'Change shape (Morph)',leftEye:'Left Eye',rightEye:'Right Eye',leftPupil:'Left Pupil',rightPupil:'Right Pupil'}[value]||value.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase()));
const repeatable=new Set(['hair','accessory']);
const groups={FACE:['head','eyes','gaze','eyelids','eyebrows','nose','mouth','jaw','ears'],OTHER:['hair','accessory']};

export function createRigPanel(host,store,history,preview,onControlCommit=()=>{},canvas,editorContext=null,navigatorHost=null){
  let selectedPart=null,tab='setup',catalogOpen=false,picking=null,session=null,notice='';
  const commands=createSemanticRigCommands(store,history), artwork=createArtworkCommands(store,history);
  const status=(part,state)=>{const def=SEMANTIC_PART_REGISTRY[part.type],assigned=def.roles.filter(role=>part.roles?.[role]&&state.elements?.[part.roles[role]]).length,invalid=part.controls.some(control=>part.controlDrivers?.[control]?.method==='morph'&&(part.controlDrivers[control].roles||[]).some(role=>{const morph=state.elements?.[part.roles[role]]?.morph;return morph?.pathA&&morph?.pathB&&!morph.compatible;}));if(invalid)return {icon:'⚠',text:'Invalid'};if(assigned===def.roles.length)return {icon:'✓',text:'Ready'};if(!assigned&&!def.controls.length)return {icon:'○',text:'Artwork only / optional'};return {icon:'●',text:'Needs setup'};};
  const selectPart=(id)=>{selectedPart=id;editorContext?.update({activeSemanticPartId:id,activeControl:null});const part=store.getDocument().semanticParts?.[id];const first=part&&Object.values(part.roles||{}).find(Boolean);if(first)store.mutateSession('selectedId',state=>{state.selectedId=first;});render();};
  const stopTransient=()=>{picking=null;session=null;notice='';preview.clearLiveParams();canvas?.cancelRigTool();render();};
  const pickRole=(role)=>{const state=store.getDocument(),part=state.semanticParts[selectedPart];if(!part)return;picking={partId:selectedPart,role};notice=`Pick artwork for ${words(role)}`;canvas.beginRolePick({label:words(role),cancel:()=>{picking=null;notice='';render();},pick:(elementId)=>{const latest=store.getDocument(),active=latest.semanticParts[picking?.partId];if(!active)return;const duplicate=Object.entries(active.roles||{}).find(([key,id])=>key!==role&&id===elementId);if(duplicate){notice=`This artwork is already used by ${words(duplicate[0])}. Choose another element.`;render();return;}commands.assignRole(active.id,role,elementId);store.mutateSession('selectedId',draft=>{draft.selectedId=elementId;});const def=SEMANTIC_PART_REGISTRY[active.type],index=def.roles.indexOf(role),next=def.roles.slice(index+1).find(key=>!store.getDocument().semanticParts[active.id].roles[key]);picking=null;canvas.cancelRigTool(false);if(next)pickRole(next);else{notice=`✓ ${words(role)} assigned`;render();}}});render();};
  // Test controls belong to PreviewSession. Resetting them must never author
  // parameter metadata or an active-state pose.
  const resetLiveControls=names=>{if(names)names.forEach(name=>preview.clearLiveParam(name));else preview.clearLiveParams();render();};

  navigatorHost?.addEventListener('click',event=>{const part=event.target.closest('[data-part]')?.dataset.part;if(part)selectPart(part);if(event.target.closest('#add-semantic-part')){catalogOpen=true;render();}if(event.target.closest('#reset-all-rig'))resetLiveControls();const role=event.target.closest('[data-role-select]')?.dataset.roleSelect;if(role){const id=store.getDocument().semanticParts[selectedPart]?.roles?.[role];if(id)store.mutateSession('selectedId',state=>{state.selectedId=id;});else pickRole(role);}});
  host.addEventListener('click',event=>{
    const target=event.target.closest('button');if(!target)return;
    if(target.dataset.rigTab){tab=target.dataset.rigTab;render();return;}
    if(target.id==='open-part-catalog'){catalogOpen=true;render();return;}
    if(target.id==='close-part-catalog'){catalogOpen=false;render();return;}
    if(target.dataset.addType){const type=target.dataset.addType,existing=Object.values(store.getDocument().semanticParts||{}).find(p=>p.type===type);if(existing&&!repeatable.has(type)){catalogOpen=false;notice=`${existing.name} already exists`;selectPart(existing.id);return;}const id=commands.createPart(type);catalogOpen=false;tab='setup';selectPart(id);return;}
    if(target.dataset.pickRole){pickRole(target.dataset.pickRole);return;}
    if(target.dataset.clearRole){commands.assignRole(selectedPart,target.dataset.clearRole,null);render();return;}
    if(target.dataset.enableControl){try{commands.enableControl(selectedPart,target.dataset.enableControl);tab='controls';notice='';}catch(error){notice=`Movement conflict: ${error.message} Manual Advanced bindings were kept.`;}render();return;}
    if(target.id==='edit-pivot'){const part=store.getDocument().semanticParts[selectedPart],id=Object.values(part.roles||{}).find(Boolean);if(!id)return;notice='Drag the ⊕ handle. The artwork will stay in place. Esc cancels.';canvas.beginPivotEdit(id,{cancel:()=>{notice='';render();},commit:point=>{artwork.setPivot(id,point.x,point.y,{source:'rig'});notice='✓ Pivot updated';render();}});render();return;}
    if(target.dataset.pivotPreset){const part=store.getDocument().semanticParts[selectedPart],id=Object.values(part.roles||{}).find(Boolean),box=canvas.getElementBounds(id);if(!id||!box)return;const map={center:[box.cx,box.cy],left:[box.x,box.cy],right:[box.x2,box.cy],top:[box.cx,box.y],bottom:[box.cx,box.y2],reset:[0,0]},point=map[target.dataset.pivotPreset];artwork.setPivot(id,...point,{source:'rig'});render();return;}
    if(target.dataset.editPose){const [control,key]=target.dataset.editPose.split(':'),part=store.getDocument().semanticParts[selectedPart],ids=Object.values(part.roles||{}).filter(Boolean);session={kind:'transform',control,key,partId:selectedPart};notice=`CALIBRATION POSE — ${words(control)} / ${words(key)}. Drag, resize, or rotate artwork.`;canvas.beginTransformPose(ids,{cancel:()=>{session=null;notice='';render();}});render();return;}
    if(target.id==='capture-pose'&&session?.kind==='transform'){const current=session,part=store.getDocument().semanticParts[current.partId],byId=canvas.captureTransformPose(),pose=Object.fromEntries(Object.entries(part.roles||{}).filter(([,id])=>byId?.[id]).map(([role,id])=>[role,byId[id]])),spec=SEMANTIC_PART_REGISTRY[part.type].calibration[current.control].poses.find(item=>item.key===current.key);commands.captureCalibration(current.partId,current.control,{key:current.key,value:spec.value,pose});session=null;notice='✓ Pose captured; Base Artwork restored.';render();return;}
    if(target.id==='cancel-rig-session'){stopTransient();return;}
    if(target.dataset.calculate){const control=target.dataset.calculate;commands.calculateCalibration(selectedPart,control);preview.clearLiveParams();render();return;}
    if(target.dataset.editMorph){const [control,pose]=target.dataset.editMorph.split(':'),part=store.getDocument().semanticParts[selectedPart],role=part.controlDrivers[control].roles.find(key=>part.roles[key]),id=part.roles[role],initial=part.calibration?.[control]?.[pose]?.[role];session={kind:'morph',control,pose,partId:selectedPart,role,id};notice=`MORPH EDIT — ${words(control)} / ${words(pose)}. Move existing nodes and Bézier handles. Topology locked.`;canvas.beginMorphPose(id,initial,{cancel:()=>{session=null;notice='';render();}});render();return;}
    if(target.id==='capture-morph-pose'&&session?.kind==='morph'){const current=session,path=canvas.captureMorphPose();commands.captureMorph(current.partId,current.control,current.pose,{[current.role]:path});session=null;notice='✓ Morph endpoint captured; Base Artwork restored.';render();return;}
    if(target.dataset.resetMorph){commands.resetMorph(selectedPart,target.dataset.resetMorph);render();return;}
    if(target.dataset.resetPart){resetLiveControls(store.getDocument().semanticParts[selectedPart].controls);return;}
    if(target.id==='reset-all-rig'){resetLiveControls();return;}
    if(target.id==='delete-semantic-part'){commands.removePart(selectedPart);selectedPart=null;editorContext?.update({activeSemanticPartId:null});render();}
  });
  host.addEventListener('input',event=>{const control=event.target.dataset.control;if(!control)return;const value=Number(event.target.value);preview.setLiveParam(control,value);const output=host.querySelector(`[data-control-output="${CSS.escape(control)}"]`);if(output)output.value=value.toFixed(2);});
  host.addEventListener('change',event=>{const control=event.target.dataset.control;if(control){const value=Number(event.target.value);preview.setLiveParam(control,value);onControlCommit(control,value);return;}const method=event.target.dataset.method;if(method){try{commands.setMethod(selectedPart,method,event.target.value);notice='';}catch(error){notice=error.message;}render();}});
  window.addEventListener('keydown',event=>{if(event.key==='Escape'&&(picking||session)){if(picking||session){event.preventDefault();stopTransient();}}});

  function renderNavigator(state,parts){if(!navigatorHost)return;navigatorHost.dataset.rigNavigatorReady="true";navigatorHost.innerHTML=`<div class="parts-tree" role="tree" aria-label="Semantic parts">${Object.values(parts).map(part=>{const def=SEMANTIC_PART_REGISTRY[part.type],s=status(part,state);return `<div class="part-tree-item ${part.id===selectedPart?'active':''}" role="treeitem" aria-selected="${part.id===selectedPart}" data-part="${esc(part.id)}" data-semantic-part-id="${esc(part.id)}"><button data-part="${esc(part.id)}"><span aria-hidden="true">${s.icon}</span><span>${esc(part.name)}<small>${s.text}</small></span></button>${part.id===selectedPart?`<div role="group">${def.roles.map(role=>`<button class="semantic-role" data-role-select="${role}">${part.roles[role]?'✓':'○'} ${words(role)}${part.roles[role]?` <small>${esc(part.roles[role])}</small>`:''}</button>`).join('')}</div>`:''}</div>`;}).join('')}</div><button id="add-semantic-part" class="add-part">+ Add Part</button><button id="reset-all-rig" class="secondary">Reset all rig controls</button>`;}
  function catalog(){return `<div class="part-catalog" role="dialog" aria-modal="true" aria-labelledby="catalog-title"><div class="card-title"><h3 id="catalog-title">Add a Part</h3><button id="close-part-catalog" aria-label="Close part catalog">×</button></div>${Object.entries(groups).map(([group,types])=>`<h4>${group}</h4><div class="part-cards">${types.map(type=>{const def=SEMANTIC_PART_REGISTRY[type],exists=Object.values(store.getDocument().semanticParts||{}).some(p=>p.type===type)&&!repeatable.has(type);return `<article><span class="part-icon" aria-hidden="true">${type==='eyes'?'◉':type==='mouth'?'⌣':'◇'}</span><div><strong>${esc(def.displayName)}</strong><p>${def.roles.length} SVG element${def.roles.length===1?'':'s'} · ${def.roles.map(words).join(', ')}</p><small>Controls: ${def.controls.length?def.controls.map(words).join(', '):'Artwork only'}</small></div><button data-add-type="${type}">${exists?'Go to Part':`Add ${esc(def.displayName)}`}</button></article>`;}).join('')}</div>`).join('')}</div>`;}
  function render(){const state=store.getDocument(),parts=state.semanticParts||{},clicked=findSemanticPartByElement(state,store.getSession().selectedId);if(clicked&&!picking)selectedPart=clicked.id;const requested=editorContext?.get().activeSemanticPartId;if(parts[requested])selectedPart=requested;if(!parts[selectedPart])selectedPart=Object.keys(parts)[0]||null;if(selectedPart&&editorContext?.get().activeSemanticPartId!==selectedPart)editorContext?.update({activeSemanticPartId:selectedPart});renderNavigator(state,parts);const part=parts[selectedPart],def=part&&SEMANTIC_PART_REGISTRY[part.type];
    if(catalogOpen){host.innerHTML=catalog();return;}if(!part){host.innerHTML=`<h2>Rig</h2><p><b>No semantic parts yet</b></p><p>Build a visual rig without typing SVG IDs.</p><button id="open-part-catalog">+ Add Part</button><details><summary>What do these steps mean?</summary><p><b>Setup</b> assigns artwork. <b>Controls</b> chooses movement. <b>Calibrate</b> defines its range. <b>Advanced</b> shows generated internals.</p></details>`;return;}
    const s=status(part,state),roles=def.roles.map(role=>`<div class="role-row"><span>${part.roles[role]?'✓':'○'} <b>${words(role)}</b><small>${esc(part.roles[role]||'Not assigned')}</small></span><span><button data-pick-role="${role}">${part.roles[role]?'Replace':'Pick artwork'}</button>${part.roles[role]?`<button class="secondary" data-clear-role="${role}">Clear</button>`:''}</span></div>`).join('');
    const controls=def.controls.map(control=>{if(!part.controls.includes(control))return `<article class="semantic-control"><b>${words(control)}</b><p>Choose and test this movement visually.</p><button data-enable-control="${control}">Enable ${words(control)}</button></article>`;const param=state.params[control],value=preview.getLiveParams()[control]??param?.default??0,driver=part.controlDrivers?.[control],strategies=def.strategies?.[control];return `<article class="semantic-control"><b>${words(control)}</b>${strategies?`<label>How should it move?<select data-method="${control}">${strategies.map(method=>`<option value="${method}" ${driver?.property===method?'selected':''}>${words(method)}</option>`).join('')}</select></label>`:''}<label>${words(control)} <output data-control-output="${control}">${Number(value).toFixed(2)}</output><input data-rig-control="${part.id}:${control}" data-control="${control}" aria-label="Test ${words(control)}" type="range" min="${param?.min??-1}" max="${param?.max??1}" step=".01" value="${value}"></label><p class="movement-guide" aria-label="Movement guide">${driver?.property==='rotation'?'↶  ●  ↷':driver?.property==='translateY'?'↑  ●  ↓':driver?.property==='scaleY'?'↕':driver?.property==='morph'?'Neutral shape ⇄ Target shape':'←  ●  →'}</p></article>`;}).join('');
    const calibration=part.controls.map(control=>{const driver=part.controlDrivers?.[control];if(driver?.method==='morph'){const poses=control==='eyeOpen'?['closed','open']:['neutral','open'],compatible=driver.roles.every(role=>state.elements?.[part.roles[role]]?.morph?.compatible);return `<article><h4>${words(control)} — Change shape</h4><p>Edit endpoints here in Rig. Topology is locked and Base Artwork is restored after Capture or Cancel.</p>${poses.map(pose=>`<button data-edit-morph="${control}:${pose}">${part.calibration?.[control]?.[pose]?'✓ ':''}Edit ${words(pose)} shape</button>`).join('')}<p class="compatibility ${compatible?'ok':'warn'}">${compatible?'✓ Compatible':'⚠ Capture both endpoints; incompatible topology remains disabled.'}</p><button class="secondary" data-reset-morph="${control}">Reset all morph calibration</button></article>`;}const poses=def.calibration?.[control]?.poses||[];if(!poses.length)return '';const samples=part.calibration?.[control]?.samples||[],captured=poses.filter(p=>samples.some(sample=>sample.key===p.key)).length;return `<article><h4>${words(control)}</h4><p>${captured} / ${poses.length} poses captured</p>${poses.map(p=>`<div class="role-row"><span>${samples.some(sample=>sample.key===p.key)?'✓':'○'} ${esc(p.label)}</span><button data-edit-pose="${control}:${p.key}">Edit pose</button></div>`).join('')}<button data-calculate="${control}" ${captured<2?'disabled':''}>Calculate movement</button></article>`;}).join('');
    const firstId=Object.values(part.roles||{}).find(Boolean),transform=state.elements?.[firstId]?.baseTransform||{};const panes={setup:`<section><h3>Setup</h3><p><b>${s.icon} ${s.text}</b></p>${roles}</section>`,controls:`<section><h3>Controls</h3>${controls||'<p>This artwork-only part has no movement controls.</p>'}<button class="secondary" data-reset-part>Reset controls</button></section>`,calibrate:`<section><h3>Calibrate</h3><p>Calibration poses are temporary authoring samples. They do not replace Base Artwork.</p><div class="pivot-card"><b>Pivot</b><p>Current: ${Number(transform.pivotX||0).toFixed(1)}, ${Number(transform.pivotY||0).toFixed(1)}</p><button id="edit-pivot" ${firstId?'':'disabled'}>Edit Pivot</button><div class="inline">${['center','left','right','top','bottom','reset'].map(name=>`<button class="secondary" data-pivot-preset="${name}" ${firstId?'':'disabled'}>${words(name)}</button>`).join('')}</div></div>${calibration||'<p>Enable a movement control first.</p>'}</section>`,advanced:`<section><h3>Advanced</h3><p>Generated bindings, ownership, pivots and raw technical details.</p><pre>${esc(JSON.stringify({roles:part.roles,controlDrivers:part.controlDrivers,calibration:part.calibration,pivot:{x:transform.pivotX||0,y:transform.pivotY||0}},null,2))}</pre></section>`};
    host.innerHTML=`${notice?`<div class="rig-instruction" role="status"><b>${esc(notice)}</b>${session?`<span><button id="${session.kind==='morph'?'capture-morph-pose':'capture-pose'}">Capture ${session.kind==='morph'?words(session.pose):'pose'}</button><button id="cancel-rig-session" class="secondary">Cancel</button></span>`:picking?'<span>Esc ×</span>':''}</div>`:''}<div class="card-title"><div><h2>${esc(part.name)}</h2><small>${s.icon} ${s.text}</small></div><button id="open-part-catalog">+ Add Part</button></div><nav class="rig-tabs" aria-label="Rig inspector">${['setup','controls','calibrate','advanced'].map(name=>`<button data-rig-tab="${name}" aria-selected="${tab===name}" class="${tab===name?'active':''}">${words(name)}</button>`).join('')}</nav>${panes[tab]}<button id="delete-semantic-part" class="danger secondary">Delete Part</button>`;}
  return {render,cancelTransient:stopTransient};
}
