import { SEMANTIC_PART_REGISTRY } from './part-registry.js';
import { findSemanticPartByElement } from './part-model.js';
import { createSemanticRigCommands } from './semantic-rig-commands.js';
import { createArtworkCommands } from '../../core/commands/artwork-commands.js';
import { calibrationPoses, movementEntry, poseInstruction } from './face-movements.js';

const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const words=value=>({lookX:'Look left / right',lookY:'Look up / down',eyeOpen:'Open / close',mouthOpen:'Open / close',headX:'Move left / right',headY:'Move up / down',headTilt:'Tilt',scaleY:'Squash vertically',scaleX:'Stretch horizontally',translateX:'Move horizontally',translateY:'Move vertically',rotation:'Rotate',morph:'Change shape (Morph)',leftEye:'Left Eye',rightEye:'Right Eye',leftPupil:'Left Pupil',rightPupil:'Right Pupil',leftBrow:'Left Eyebrow',rightBrow:'Right Eyebrow'}[value]||value.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase()));
const repeatable=new Set(['hair','accessory']);
const groups={FACE:['head','eyes','gaze','eyelids','eyebrows','nose','mouth','jaw','ears'],OTHER:['hair','accessory']};

export function createRigPanel(host,store,history,preview,onControlCommit=()=>{},canvas,editorContext=null,navigatorHost=null){
  let selectedPart=null,tab='setup',catalogOpen=false,picking=null,session=null,notice='';
  const commands=createSemanticRigCommands(store,history), artwork=createArtworkCommands(store,history);
  const status=(part,state)=>{const def=SEMANTIC_PART_REGISTRY[part.type],assigned=def.roles.filter(role=>part.roles?.[role]&&state.elements?.[part.roles[role]]).length,invalid=part.controls.some(control=>part.controlDrivers?.[control]?.method==='morph'&&(part.controlDrivers[control].roles||[]).some(role=>{const morph=state.elements?.[part.roles[role]]?.morph;return morph?.pathA&&morph?.pathB&&!morph.compatible;}));if(invalid)return {icon:'⚠',text:'Invalid'};if(assigned===def.roles.length)return {icon:'✓',text:'Ready'};if(!assigned&&!def.controls.length)return {icon:'○',text:'Artwork only / optional'};return {icon:'●',text:'Needs setup'};};
  const selectPart=(id)=>{selectedPart=id;editorContext?.update({activeSemanticPartId:id,activeControl:null});const part=store.getDocument().semanticParts?.[id];const first=part&&Object.values(part.roles||{}).find(Boolean);if(first)store.mutateSession('selectedId',state=>{state.selectedId=first;});render();};
  const stopTransient=()=>{picking=null;session=null;notice='';canvas?.cancelRigTool();render();};
  const cancelTransient=()=>{if(!picking&&!session)return;stopTransient();};
  const pickRole=(role)=>{const state=store.getDocument(),part=state.semanticParts[selectedPart];if(!part)return;picking={partId:selectedPart,role};notice=`Pick artwork for ${words(role)}`;canvas.beginRolePick({label:words(role),cancel:()=>{picking=null;notice='';render();},pick:(elementId)=>{const latest=store.getDocument(),active=latest.semanticParts[picking?.partId];if(!active)return;const duplicate=Object.entries(active.roles||{}).find(([key,id])=>key!==role&&id===elementId);if(duplicate){notice=`This artwork is already used by ${words(duplicate[0])}. Choose another element.`;render();return;}commands.assignRole(active.id,role,elementId);store.mutateSession('selectedId',draft=>{draft.selectedId=elementId;});const def=SEMANTIC_PART_REGISTRY[active.type],index=def.roles.indexOf(role),next=def.roles.slice(index+1).find(key=>!store.getDocument().semanticParts[active.id].roles[key]);picking=null;canvas.cancelRigTool(false);if(next)pickRole(next);else{notice=`✓ ${words(role)} assigned`;render();}}});render();};
  // Test controls belong to PreviewSession. Resetting them must never author
  // parameter metadata or an active-state pose.
  const resetLiveControls=names=>{if(names)names.forEach(name=>preview.clearLiveParam(name));else preview.clearLiveParams();render();};
  // One capture path for the inspector button and the Canvas banner. Visual
  // calibration solves the movement as soon as two poses exist (one undo step).
  const capturePose=()=>{if(session?.kind!=='transform')return;const current=session,part=store.getDocument().semanticParts[current.partId],byId=canvas.captureTransformPose(),pose=Object.fromEntries(Object.entries(part.roles||{}).filter(([,id])=>byId?.[id]).map(([role,id])=>[role,byId[id]])),spec=calibrationPoses(part.type,current.control,part.controlDrivers?.[current.control]).find(item=>item.key===current.key);session=null;if(!spec){notice='';render();return;}if(current.auto){const solved=commands.captureAndCalibrate(current.partId,current.control,{key:current.key,value:spec.value,pose});notice=solved?`✓ ${spec.label} captured — movement calibrated. Test it below.`:`✓ ${spec.label} captured. Capture one more pose to calibrate.`;}else{commands.captureCalibration(current.partId,current.control,{key:current.key,value:spec.value,pose});notice='✓ Pose captured; Base Artwork restored.';}render();};
  const captureMorph=()=>{if(session?.kind!=='morph')return;const current=session,path=canvas.captureMorphPose();commands.captureMorph(current.partId,current.control,current.pose,{[current.role]:path});session=null;notice='✓ Shape captured; Base Artwork restored.';render();};
  const beginPoseCapture=(control,key,auto)=>{const part=store.getDocument().semanticParts[selectedPart],ids=Object.values(part.roles||{}).filter(Boolean),entry=movementEntry(control),spec=calibrationPoses(part.type,control,part.controlDrivers?.[control]).find(item=>item.key===key);if(!ids.length||!spec)return;session={kind:'transform',control,key,partId:selectedPart,auto};const instruction=entry?poseInstruction(entry,spec):`${words(control)} / ${spec.label}: pose the artwork, then press Capture.`;notice=auto?instruction:`CALIBRATION POSE — ${words(control)} / ${words(key)}. Drag, resize, or rotate artwork.`;canvas.beginTransformPose(ids,{cancel:()=>{session=null;notice='';render();},instruction,capture:capturePose});render();};

  navigatorHost?.addEventListener('click',event=>{const part=event.target.closest('[data-part]')?.dataset.part;if(part)selectPart(part);if(event.target.closest('#add-semantic-part')){catalogOpen=true;render();}if(event.target.closest('#reset-all-rig'))resetLiveControls();const role=event.target.closest('[data-role-select]')?.dataset.roleSelect;if(role){const id=store.getDocument().semanticParts[selectedPart]?.roles?.[role];if(id)store.mutateSession('selectedId',state=>{state.selectedId=id;});else pickRole(role);}});
  host.addEventListener('click',event=>{
    const target=event.target.closest('button');if(!target)return;
    if(target.dataset.rigTab){tab=target.dataset.rigTab;render();return;}
    if(target.id==='open-part-catalog'){catalogOpen=true;render();return;}
    if(target.id==='close-part-catalog'){catalogOpen=false;render();return;}
    if(target.dataset.addType){const type=target.dataset.addType,existing=Object.values(store.getDocument().semanticParts||{}).find(p=>p.type===type);if(existing&&!repeatable.has(type)){catalogOpen=false;notice=`${existing.name} already exists`;selectPart(existing.id);return;}const id=commands.createPart(type);catalogOpen=false;tab='setup';selectPart(id);return;}
    if(target.dataset.pickRole){pickRole(target.dataset.pickRole);return;}
    if(target.dataset.clearRole){commands.assignRole(selectedPart,target.dataset.clearRole,null);render();return;}
    if(target.dataset.enableControl){try{commands.enableControl(selectedPart,target.dataset.enableControl);tab='controls';notice='';}catch(error){notice=`Movement conflict: ${error.message} Manual Advanced bindings were kept.`;}render();return;}
    if(target.id==='edit-pivot'){const part=store.getDocument().semanticParts[selectedPart],id=Object.values(part.roles||{}).find(Boolean);if(!id)return;notice='Drag the ⊕ handle. The artwork will stay in place. Esc cancels.';canvas.beginPivotEdit(id,{cancel:()=>{notice='';render();},commit:point=>{artwork.setPivot(id,point.x,point.y,{source:'rig'});notice='✓ Pivot updated';render();}});render();return;}
    if(target.dataset.pivotPreset){const part=store.getDocument().semanticParts[selectedPart],id=Object.values(part.roles||{}).find(Boolean),box=canvas.getElementBounds(id);if(!id||!box)return;const map={center:[box.cx,box.cy],left:[box.x,box.cy],right:[box.x2,box.cy],top:[box.cx,box.y],bottom:[box.cx,box.y2],reset:[0,0]},point=map[target.dataset.pivotPreset];artwork.setPivot(id,...point,{source:'rig'});render();return;}
    if(target.dataset.editPose){const [control,key]=target.dataset.editPose.split(':');beginPoseCapture(control,key,false);return;}
    if(target.dataset.poseCapture){const [control,key]=target.dataset.poseCapture.split(':');beginPoseCapture(control,key,true);return;}
    if(target.id==='capture-pose'&&session?.kind==='transform'){capturePose();return;}
    if(target.dataset.movementBack!==undefined){editorContext?.update({activeControl:null});render();return;}
    if(target.dataset.resetCalibration){try{commands.resetCalibration(selectedPart,target.dataset.resetCalibration);preview.clearLiveParams();notice='Calibration reset. The default movement is back.';}catch(error){notice=error.message;}render();return;}
    if(target.dataset.disableControl){try{commands.disableControl(selectedPart,target.dataset.disableControl);preview.clearLiveParams();editorContext?.update({activeControl:null});notice='';}catch(error){notice=error.message;}render();return;}
    if(target.id==='cancel-rig-session'){stopTransient();return;}
    if(target.dataset.calculate){const control=target.dataset.calculate;commands.calculateCalibration(selectedPart,control);preview.clearLiveParams();render();return;}
    if(target.dataset.editMorph){const [control,pose]=target.dataset.editMorph.split(':'),part=store.getDocument().semanticParts[selectedPart],role=part.controlDrivers[control].roles.find(key=>part.roles[key]),id=part.roles[role],initial=part.calibration?.[control]?.[pose]?.[role];if(!id)return;session={kind:'morph',control,pose,partId:selectedPart,role,id};notice=`Shape for ${words(control)} / ${words(pose)}: move the nodes into the target shape, then press Capture. Topology stays locked.`;canvas.beginMorphPose(id,initial,{cancel:()=>{session=null;notice='';render();},instruction:notice,capture:captureMorph});render();return;}
    if(target.id==='capture-morph-pose'&&session?.kind==='morph'){captureMorph();return;}
    if(target.dataset.resetMorph){commands.resetMorph(selectedPart,target.dataset.resetMorph);render();return;}
    if(target.dataset.resetPart!==undefined){resetLiveControls(store.getDocument().semanticParts[selectedPart]?.controls);return;}
    if(target.id==='reset-all-rig'){resetLiveControls();return;}
    if(target.id==='delete-semantic-part'){commands.removePart(selectedPart);selectedPart=null;editorContext?.update({activeSemanticPartId:null});render();}
  });
  host.addEventListener('input',event=>{const control=event.target.dataset.control;if(!control)return;const value=Number(event.target.value);preview.setLiveParam(control,value);const output=host.querySelector(`[data-control-output="${CSS.escape(control)}"]`);if(output)output.value=value.toFixed(2);});
  host.addEventListener('change',event=>{const control=event.target.dataset.control;if(control){const value=Number(event.target.value);preview.setLiveParam(control,value);onControlCommit(control,value);return;}const method=event.target.dataset.method;if(method){try{commands.setMethod(selectedPart,method,event.target.value);notice='';}catch(error){notice=error.message;}render();}});
  window.addEventListener('keydown',event=>{if(event.key==='Escape'&&(picking||session)){if(picking||session){event.preventDefault();stopTransient();}}});
  // XY test pad: pointer drag drives two live params; release commits once (Auto Key aware).
  let padActive=null;
  const applyPad=(pad,event)=>{const [xName,yName]=pad.dataset.xy.split(':'),box=pad.getBoundingClientRect(),clamp=v=>Math.max(-1,Math.min(1,v)),x=clamp(((event.clientX-box.left)/box.width)*2-1),y=clamp(((event.clientY-box.top)/box.height)*2-1);preview.setLiveParam(xName,x);preview.setLiveParam(yName,y);pad.style.setProperty('--x',`${(x+1)*50}%`);pad.style.setProperty('--y',`${(y+1)*50}%`);for(const [name,value] of [[xName,x],[yName,y]]){const input=host.querySelector(`[data-control="${CSS.escape(name)}"]`),output=host.querySelector(`[data-control-output="${CSS.escape(name)}"]`);if(input)input.value=String(value);if(output)output.value=value.toFixed(2);}};
  host.addEventListener('pointerdown',event=>{const pad=event.target.closest('.xy-pad');if(!pad||event.button!==0)return;event.preventDefault();pad.setPointerCapture(event.pointerId);padActive=pad;applyPad(pad,event);});
  host.addEventListener('pointermove',event=>{if(padActive&&padActive.hasPointerCapture(event.pointerId))applyPad(padActive,event);});
  host.addEventListener('pointerup',event=>{if(!padActive)return;const [xName,yName]=padActive.dataset.xy.split(':'),live=preview.getLiveParams();padActive.releasePointerCapture?.(event.pointerId);padActive=null;onControlCommit(xName,live[xName]??0);onControlCommit(yName,live[yName]??0);});
  host.addEventListener('keydown',event=>{const pad=event.target.closest?.('.xy-pad');if(!pad)return;const step={ArrowLeft:[-.1,0],ArrowRight:[.1,0],ArrowUp:[0,-.1],ArrowDown:[0,.1]}[event.key];if(!step)return;event.preventDefault();const [xName,yName]=pad.dataset.xy.split(':'),live=preview.getLiveParams(),x=Math.max(-1,Math.min(1,(live[xName]??0)+step[0])),y=Math.max(-1,Math.min(1,(live[yName]??0)+step[1]));preview.setLiveParam(xName,x);preview.setLiveParam(yName,y);onControlCommit(xName,x);onControlCommit(yName,y);render();host.querySelector('.xy-pad')?.focus();});

  function renderNavigator(state,parts){if(!navigatorHost)return;navigatorHost.dataset.rigNavigatorReady="true";navigatorHost.innerHTML=`<div class="parts-tree" role="tree" aria-label="Face parts">${Object.values(parts).map(part=>{const def=SEMANTIC_PART_REGISTRY[part.type],s=status(part,state);return `<div class="part-tree-item ${part.id===selectedPart?'active':''}" role="treeitem" aria-selected="${part.id===selectedPart}" data-part="${esc(part.id)}" data-semantic-part-id="${esc(part.id)}"><button data-part="${esc(part.id)}"><span aria-hidden="true">${s.icon}</span><span>${esc(part.name)}<small>${s.text}</small></span></button>${part.id===selectedPart?`<div role="group">${def.roles.map(role=>`<button class="semantic-role" data-role-select="${role}">${part.roles[role]?'✓':'○'} ${words(role)}${part.roles[role]?` <small>${esc(part.roles[role])}</small>`:''}</button>`).join('')}</div>`:''}</div>`;}).join('')}</div><button id="add-semantic-part" class="add-part">+ Add Part</button><button id="reset-all-rig" class="secondary">Reset test controls</button>`;}
  function catalog(){return `<div class="part-catalog" role="dialog" aria-modal="true" aria-labelledby="catalog-title"><div class="card-title"><h3 id="catalog-title">Add a Part</h3><button id="close-part-catalog" aria-label="Close part catalog">×</button></div>${Object.entries(groups).map(([group,types])=>`<h4>${group}</h4><div class="part-cards">${types.map(type=>{const def=SEMANTIC_PART_REGISTRY[type],exists=Object.values(store.getDocument().semanticParts||{}).some(p=>p.type===type)&&!repeatable.has(type);return `<article><span class="part-icon" aria-hidden="true">${type==='eyes'?'◉':type==='mouth'?'⌣':'◇'}</span><div><strong>${esc(def.displayName)}</strong><p>${def.roles.length} SVG element${def.roles.length===1?'':'s'} · ${def.roles.map(words).join(', ')}</p><small>Controls: ${def.controls.length?def.controls.map(words).join(', '):'Artwork only'}</small></div><button data-add-type="${type}">${exists?'Go to Part':`Add ${esc(def.displayName)}`}</button></article>`;}).join('')}</div>`).join('')}</div>`;}
  function render(){const state=store.getDocument(),parts=state.semanticParts||{},clicked=findSemanticPartByElement(state,store.getSession().selectedId);if(clicked&&!picking)selectedPart=clicked.id;const requested=editorContext?.get().activeSemanticPartId;if(parts[requested])selectedPart=requested;if(!parts[selectedPart])selectedPart=Object.keys(parts)[0]||null;if(selectedPart&&editorContext?.get().activeSemanticPartId!==selectedPart)editorContext?.update({activeSemanticPartId:selectedPart});renderNavigator(state,parts);const part=parts[selectedPart],def=part&&SEMANTIC_PART_REGISTRY[part.type];
    if(catalogOpen){host.innerHTML=catalog();return;}if(!part){host.innerHTML=`<h2>Face Setup</h2><p><b>No face parts yet</b></p><p>Use the Face parts checklist: choose a part, then click its artwork on the canvas. Other parts (eyelids, jaw, hair…) can be added here.</p><button id="open-part-catalog">+ Add Part</button><details><summary>What do these steps mean?</summary><p><b>Setup</b> assigns artwork. <b>Controls</b> chooses movement. <b>Calibrate</b> defines its range. <b>Advanced</b> shows generated internals.</p></details>`;return;}
    const s=status(part,state),roles=def.roles.map(role=>`<div class="role-row"><span>${part.roles[role]?'✓':'○'} <b>${words(role)}</b><small>${esc(part.roles[role]||'Not assigned')}</small></span><span><button data-pick-role="${role}">${part.roles[role]?'Replace':'Pick artwork'}</button>${part.roles[role]?`<button class="secondary" data-clear-role="${role}">Clear</button>`:''}</span></div>`).join('');
    const controls=def.controls.map(control=>{if(!part.controls.includes(control))return `<article class="semantic-control"><b>${words(control)}</b><p>Choose and test this movement visually.</p><button data-enable-control="${control}">Enable ${words(control)}</button></article>`;const param=state.params[control],value=preview.getLiveParams()[control]??param?.default??0,driver=part.controlDrivers?.[control],strategies=def.strategies?.[control];return `<article class="semantic-control"><b>${words(control)}</b>${strategies?`<label>How should it move?<select data-method="${control}">${strategies.map(method=>`<option value="${method}" ${driver?.property===method?'selected':''}>${words(method)}</option>`).join('')}</select></label>`:''}<label>${words(control)} <output data-control-output="${control}">${Number(value).toFixed(2)}</output><input data-rig-control="${part.id}:${control}" data-control="${control}" aria-label="Test ${words(control)}" type="range" min="${param?.min??-1}" max="${param?.max??1}" step=".01" value="${value}"></label><p class="movement-guide" aria-label="Movement guide">${driver?.property==='rotation'?'↶  ●  ↷':driver?.property==='translateY'?'↑  ●  ↓':driver?.property==='scaleY'?'↕':driver?.property==='morph'?'Neutral shape ⇄ Target shape':'←  ●  →'}</p></article>`;}).join('');
    const calibration=part.controls.map(control=>{const driver=part.controlDrivers?.[control];if(driver?.method==='morph'){const poses=control==='eyeOpen'?['closed','open']:['neutral','open'],compatible=driver.roles.every(role=>state.elements?.[part.roles[role]]?.morph?.compatible);return `<article><h4>${words(control)} — Change shape</h4><p>Edit endpoints here in Rig. Topology is locked and Base Artwork is restored after Capture or Cancel.</p>${poses.map(pose=>`<button data-edit-morph="${control}:${pose}">${part.calibration?.[control]?.[pose]?'✓ ':''}Edit ${words(pose)} shape</button>`).join('')}<p class="compatibility ${compatible?'ok':'warn'}">${compatible?'✓ Compatible':'⚠ Capture both endpoints; incompatible topology remains disabled.'}</p><button class="secondary" data-reset-morph="${control}">Reset all morph calibration</button></article>`;}const poses=def.calibration?.[control]?.poses||[];if(!poses.length)return '';const samples=part.calibration?.[control]?.samples||[],captured=poses.filter(p=>samples.some(sample=>sample.key===p.key)).length;return `<article><h4>${words(control)}</h4><p>${captured} / ${poses.length} poses captured</p>${poses.map(p=>`<div class="role-row"><span>${samples.some(sample=>sample.key===p.key)?'✓':'○'} ${esc(p.label)}</span><button data-edit-pose="${control}:${p.key}">Edit pose</button></div>`).join('')}<button data-calculate="${control}" ${captured<2?'disabled':''}>Calculate movement</button></article>`;}).join('');
    const firstId=Object.values(part.roles||{}).find(Boolean),transform=state.elements?.[firstId]?.baseTransform||{};const panes={setup:`<section><h3>Setup</h3><p><b>${s.icon} ${s.text}</b></p>${roles}</section>`,controls:`<section><h3>Controls</h3>${controls||'<p>This artwork-only part has no movement controls.</p>'}<button class="secondary" data-reset-part>Reset controls</button></section>`,calibrate:`<section><h3>Calibrate</h3><p>Calibration poses are temporary authoring samples. They do not replace Base Artwork.</p><div class="pivot-card"><b>Pivot</b><p>Current: ${Number(transform.pivotX||0).toFixed(1)}, ${Number(transform.pivotY||0).toFixed(1)}</p><button id="edit-pivot" ${firstId?'':'disabled'}>Edit Pivot</button><div class="inline">${['center','left','right','top','bottom','reset'].map(name=>`<button class="secondary" data-pivot-preset="${name}" ${firstId?'':'disabled'}>${words(name)}</button>`).join('')}</div></div>${calibration||'<p>Enable a movement control first.</p>'}</section>`,advanced:`<section><h3>Advanced</h3><p>Generated bindings, ownership, pivots and raw technical details.</p><pre>${esc(JSON.stringify({roles:part.roles,controlDrivers:part.controlDrivers,calibration:part.calibration,pivot:{x:transform.pivotX||0,y:transform.pivotY||0}},null,2))}</pre></section>`};
    const instructionBlock=notice?`<div class="rig-instruction" role="status"><b>${esc(notice)}</b>${session?`<span><button id="${session.kind==='morph'?'capture-morph-pose':'capture-pose'}">Capture ${session.kind==='morph'?words(session.pose):'pose'}</button><button id="cancel-rig-session" class="secondary">Cancel</button></span>`:picking?'<span>Esc ×</span>':''}</div>`:'';
    const movement=editorContext?.get().activeControl;
    if(movement&&def.controls.includes(movement)){host.innerHTML=`${instructionBlock}${movementView(part,def,movement,state)}`;return;}
    host.innerHTML=`${instructionBlock}<div class="card-title"><div><h2>${esc(part.name)}</h2><small>${s.icon} ${s.text}</small></div><button id="open-part-catalog">+ Add Part</button></div><nav class="rig-tabs" aria-label="Face part sections">${['setup','controls','calibrate','advanced'].map(name=>`<button data-rig-tab="${name}" aria-selected="${tab===name}" class="${tab===name?'active':''}">${words(name)}</button>`).join('')}</nav>${panes[tab]}<button id="delete-semantic-part" class="danger secondary">Delete Part</button>`;}
  // Movement Inspector: one control of one part — test, visual calibration, Advanced.
  function movementView(part,def,control,state){
    const entry=movementEntry(control),label=entry?.label||words(control),enabled=part.controls.includes(control),driver=part.controlDrivers?.[control],param=state.params[control];
    const back=`<button type="button" class="secondary" data-movement-back aria-label="Back to ${esc(part.name)}">← ${esc(part.name)}</button>`;
    if(!enabled)return `${back}<div class="card-title"><h2>${esc(label)}</h2><small>○ Off</small></div><p>This movement is off. Turn it on to test it and calibrate it visually.</p><button type="button" data-enable-control="${control}">Turn on ${esc(label)}</button>`;
    const slider=(name)=>{const p=state.params[name],v=preview.getLiveParams()[name]??p?.default??0,l=movementEntry(name)?.label||words(name);return `<label>${esc(l)} <output data-control-output="${name}">${Number(v).toFixed(2)}</output><input data-rig-control="${part.id}:${name}" data-control="${name}" aria-label="Test ${esc(l)}" type="range" min="${p?.min??-1}" max="${p?.max??1}" step=".01" value="${v}"></label>`;};
    const pair=entry?.pair&&part.controls.includes(entry.pair)?entry.pair:null;
    const [xName,yName]=pair?(entry.axis==='x'?[control,pair]:[pair,control]):[null,null];
    const xy=pair?`<div class="xy-pad" data-xy="${xName}:${yName}" role="application" aria-label="Test pad: ${esc(movementEntry(xName)?.label||xName)} and ${esc(movementEntry(yName)?.label||yName)}. Use arrow keys or drag." tabindex="0" style="--x:${((preview.getLiveParams()[xName]??0)+1)*50}%;--y:${((preview.getLiveParams()[yName]??0)+1)*50}%"><i></i></div>`:'';
    const poses=calibrationPoses(part.type,control,driver),record=part.calibration?.[control],capturedKeys=driver?.method==='morph'?Object.keys(record||{}):(record?.samples||[]).map(x=>x.key),captured=poses.filter(p=>capturedKeys.includes(p.key)).length;
    const calibrated=driver?.method==='morph'?captured===poses.length&&poses.length>0:captured>=2;
    const cards=poses.map(pose=>{const done=capturedKeys.includes(pose.key);return `<div class="pose-card" data-pose="${pose.key}" data-pose-captured="${done}"><span>${done?'✓':'○'} <b>${esc(pose.label)}</b></span>${driver?.method==='morph'?`<button type="button" class="${done?'secondary':''}" data-edit-morph="${control}:${pose.key}">${done?'Edit again':'Edit shape'}</button>`:`<button type="button" class="${done?'secondary':''}" data-pose-capture="${control}:${pose.key}" aria-label="${done?'Capture again':'Pose and capture'} ${esc(pose.label)}">${done?'Capture again':'Pose & capture'}</button>`}</div>`;}).join('');
    const bindings=(driver?.roles||[]).map(role=>{const id=part.roles[role],b=state.elements?.[id]?.bindings?.[driver.property];return b?`<li>${esc(words(role))} · ${esc(driver.property)} · amplitude ${Number(b.amplitude).toFixed(2)} · offset ${Number(b.offset).toFixed(2)}</li>`:'';}).join('');
    const compatibility=driver?.method==='morph'?`<p class="compatibility ${driver.roles.every(role=>state.elements?.[part.roles[role]]?.morph?.compatible)?'ok':'warn'}">${driver.roles.every(role=>state.elements?.[part.roles[role]]?.morph?.compatible)?'✓ Shapes are compatible':'⚠ Capture both shapes with the same node layout.'}</p>`:'';
    return `${back}<div class="card-title"><h2>${esc(label)}</h2><small data-movement-status="${calibrated?'calibrated':captured?'partial':'default'}">${calibrated?'✓ Calibrated':captured?`● ${captured} / ${poses.length} poses`:'○ Default movement'}</small></div>
      <section class="movement-test"><h3>Test</h3>${xy}${slider(control)}${pair?slider(pair):''}<button type="button" class="secondary" data-reset-part>Center</button></section>
      <section class="movement-calibrate"><h3>Calibrate</h3><p class="small">${driver?.method==='morph'?'Edit the shape for each endpoint. Base artwork is restored afterwards.':'Pose the artwork for each position and capture it. Two poses are enough; the movement updates immediately.'}</p><div class="pose-cards">${cards}</div>${compatibility}${captured?`<button type="button" class="secondary" data-reset-calibration="${control}">Reset to default movement</button>`:''}</section>
      <details class="movement-advanced"><summary>Advanced</summary>${def.strategies?.[control]?`<label>How should it move?<select data-method="${control}">${def.strategies[control].map(m=>`<option value="${m}" ${driver?.property===m?'selected':''}>${words(m)}</option>`).join('')}</select></label>`:''}<ul class="small">${bindings||'<li>No generated binding yet.</li>'}</ul><button type="button" class="danger secondary" data-disable-control="${control}">Turn off ${esc(label)}</button></details>`;
  }
  // Checklist rows open a part on a given section without a second inspector.
  const openPart=(id,nextTab='setup')=>{if(!store.getDocument().semanticParts?.[id])return;tab=nextTab;catalogOpen=false;selectPart(id);};
  const openMovement=(id,control)=>{if(!store.getDocument().semanticParts?.[id])return;catalogOpen=false;selectPart(id);editorContext?.update({activeSemanticPartId:id,activeControl:control});render();};
  return {render,cancelTransient,openPart,openMovement};
}
