import { chromium } from 'playwright';
const SHOT = process.env.SHOT;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', e => errors.push('PAGEERROR ' + e.message));
page.on('console', m => { if (m.type() === 'error') errors.push('CONSOLE ' + m.text()); });
await page.goto('http://127.0.0.1:4173/Boop-mascotte/?e2e=1');
await page.waitForTimeout(700);
await page.getByRole('button', { name: /Expressive Face/i }).first().click();
await page.waitForTimeout(1400);
await page.locator('[data-task="face-setup"]').click();
await page.waitForTimeout(600);
console.log('offer visible:', await page.locator('[data-halo-generate]').isVisible().catch(() => false));
await page.screenshot({ path: SHOT + '/J0-offer.png' });
await page.locator('[data-halo-generate]').click();
await page.waitForTimeout(900);
console.log('keyforms after clicking:', await page.evaluate(() => (window.__BOOP_E2E__.document().keyforms || []).length));
console.log('dots now:', await page.locator('.puppet-halo [data-halo-cell]').count());
console.log('offer gone:', (await page.locator('[data-halo-generate]').count()) === 0);
await page.evaluate(() => window.__BOOP_E2E__.setLiveParam('headX', 1));
await page.waitForTimeout(400);
await page.screenshot({ path: SHOT + '/J1-turned.png' });
console.log('ERRORS', JSON.stringify(errors.slice(0, 4)));
await browser.close();
