import test from 'node:test';import assert from 'node:assert/strict';
import { availableExamples } from '../sample/example-registry.js';
import { FACE_FEATURES,isFaceFeatureInstalled } from '../sample/face-features.js';
import { findSemanticPartByElement } from '../../rig-editor/semantic-parts/part-model.js';
import { BASIC_FACE_SVG, EXPRESSIVE_FACE_SVG, TALKING_FACE_SVG } from '../sample/templates/face-artwork.js';
test('example registry exposes only clips present in the project',()=>{const state={animationClips:[{id:'blink-clip',name:'Blink'},{id:'missing',name:'Dead'}]};assert.deepEqual(availableExamples(state).map(x=>x.name),['Blink']);});
test('feature detection derives installation from semantic roles and artwork',()=>{const state={elements:{browLeft:{},browRight:{}},semanticParts:{eyebrows:{roles:{leftBrow:'browLeft',rightBrow:'browRight'}}}};assert.equal(isFaceFeatureInstalled(state,'eyebrows'),true);delete state.elements.browRight;assert.equal(isFaceFeatureInstalled(state,'eyebrows'),false);assert.ok(FACE_FEATURES.eyelids.exampleClips.some(c=>c.name==='Natural Blink'));});
test('built-in faces and progressive features share the faceRoot contract',()=>{for(const svg of [BASIC_FACE_SVG,EXPRESSIVE_FACE_SVG,TALKING_FACE_SVG])assert.match(svg,/<g id="faceRoot"/);assert.equal(FACE_FEATURES.eyebrows.mountPoint,'faceRoot');assert.equal(FACE_FEATURES.eyelids.mountPoint,'faceRoot');});
test('canvas artwork resolves to its most specific semantic Face Part',()=>{const state={layers:[{id:'faceRoot',children:[{id:'head',children:[]},{id:'eyes',children:[{id:'pupilLeft',children:[]}]}]}],semanticParts:{head:{id:'head-part',roles:{head:'faceRoot'}},gaze:{id:'gaze',roles:{leftPupil:'pupilLeft'}}}};assert.equal(findSemanticPartByElement(state,'pupilLeft').id,'gaze');assert.equal(findSemanticPartByElement(state,'head').id,'head-part');assert.equal(findSemanticPartByElement(state,'missing'),null);});
