import { createClip, duplicateClip, removeClip, addTrack, removeTrack, upsertKeyframe, deleteKeyframe } from './clip-operations.js';
const esc=(v)=>String(v).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createTimelinePanel(host, store, history, preview) {
  let selectedKey=null;
  const mutate=(fn)=>{history.snapshot();store.setState(fn);};
  const active=(state=store.getState())=>state.animationClips.find((c)=>c.id===state.animationEditor.activeClipId);
  host.addEventListener('click',(event)=>{ const state=store.getState(),clip=active(state);
    if(event.target.id==='new-clip') mutate((d)=>{const c=createClip(d.animationClips);d.animationEditor.activeClipId=c.id;});
    if(event.target.id==='duplicate-clip'&&clip) mutate((d)=>{const c=duplicateClip(d.animationClips,clip.id);d.animationEditor.activeClipId=c.id;});
    if(event.target.id==='delete-clip'&&clip) mutate((d)=>{removeClip(d.animationClips,clip.id);d.animationEditor.activeClipId=d.animationClips[0]?.id||null;});
    if(event.target.id==='add-track'&&clip){const p=host.querySelector('#track-param').value;mutate((d)=>addTrack(active(d),p));}
    if(event.target.dataset.removeTrack) mutate((d)=>removeTrack(active(d),event.target.dataset.removeTrack));
    if(event.target.dataset.addKey) {const p=event.target.dataset.addKey,value=preview.getEffectiveParams()[p]??state.params[p]?.value??0;mutate((d)=>upsertKeyframe(active(d),p,d.animationEditor.playhead,value));}
    if(event.target.dataset.key){const [p,t]=event.target.dataset.key.split('|');selectedKey={parameter:p,time:Number(t)};render();}
    if(event.target.id==='delete-key'&&selectedKey){mutate((d)=>deleteKeyframe(active(d),selectedKey.parameter,selectedKey.time));selectedKey=null;}
    if(event.target.id==='clip-play'){preview.setClip(clip?.id);preview.seek(state.animationEditor.playhead);preview.playClip();}
    if(event.target.id==='clip-pause')preview.pauseClip(); if(event.target.id==='clip-stop'){preview.stopClip();mutate((d)=>{d.animationEditor.playhead=0;});}
  });
  host.addEventListener('input',(event)=>{if(event.target.id==='playhead'){const time=Number(event.target.value);store.getState().animationEditor.playhead=time;preview.seek(time);host.querySelector('#current-time').textContent=time.toFixed(2);}});
  host.addEventListener('change',(event)=>{const clip=active(); if(event.target.id==='active-clip'){mutate((d)=>{d.animationEditor.activeClipId=event.target.value;d.animationEditor.playhead=0;});preview.setClip(event.target.value);}
    if(event.target.id==='clip-name'&&clip)mutate((d)=>{active(d).name=event.target.value.trim()||clip.name;}); if(event.target.id==='clip-duration'&&Number(event.target.value)>0)mutate((d)=>{active(d).duration=Number(event.target.value);}); if(event.target.id==='clip-loop')mutate((d)=>{active(d).loop=event.target.checked;});
    if(event.target.id==='playhead'){store.setState((d)=>{d.animationEditor.playhead=Number(event.target.value);});}
    if(event.target.dataset.keyEdit&&selectedKey)mutate((d)=>{const c=active(d),frame=c.tracks[selectedKey.parameter].find((f)=>Math.abs(f.time-selectedKey.time)<1e-6);if(event.target.dataset.keyEdit==='time'){frame.time=Math.max(0,Math.min(c.duration,Number(event.target.value)));selectedKey.time=frame.time;c.tracks[selectedKey.parameter].sort((a,b)=>a.time-b.time);}else if(event.target.dataset.keyEdit==='value')frame.value=Number(event.target.value);else frame.easing=event.target.value;});
  });
  function render(){const state=store.getState(),clip=active(state),params=Object.keys(state.params),playhead=Math.min(state.animationEditor.playhead,clip?.duration||1);preview.setClip(clip?.id||null);host.innerHTML=`<div class="timeline-head"><h3>Timeline</h3><select id="active-clip">${state.animationClips.map((c)=>`<option value="${esc(c.id)}" ${c===clip?'selected':''}>${esc(c.name)}</option>`).join('')}</select><button id="new-clip">+ New Clip</button><button id="duplicate-clip" ${clip?'':'disabled'}>Duplicate</button><button id="delete-clip" class="danger" ${clip?'':'disabled'}>Delete</button></div>${clip?`<div class="inline"><label>Name<input id="clip-name" value="${esc(clip.name)}"></label><label>Duration<input id="clip-duration" type="number" min=".01" step=".1" value="${clip.duration}"></label><label class="check"><input id="clip-loop" type="checkbox" ${clip.loop?'checked':''}> Loop</label><button id="clip-play">▶</button><button id="clip-pause">Ⅱ</button><button id="clip-stop">■</button></div><label>Current <span id="current-time">${playhead.toFixed(2)}</span>s<input id="playhead" type="range" min="0" max="${clip.duration}" step=".01" value="${playhead}"></label><div class="inline"><select id="track-param">${params.filter((p)=>!clip.tracks[p]).map((p)=>`<option>${esc(p)}</option>`).join('')}</select><button id="add-track" ${params.some((p)=>!clip.tracks[p])?'':'disabled'}>+ Track</button><label class="check"><input id="auto-key" type="checkbox" ${state.animationEditor.autoKey?'checked':''}> ● Auto Key</label></div>${Object.entries(clip.tracks).map(([p,frames])=>`<div class="track"><strong>${esc(p)}</strong><button data-add-key="${esc(p)}">+ ◆ at playhead</button><button data-remove-track="${esc(p)}" class="icon danger">×</button><div class="key-lane">${frames.map((f)=>`<button class="key ${selectedKey?.parameter===p&&selectedKey.time===f.time?'selected':''}" style="left:${f.time/clip.duration*100}%" data-key="${esc(p)}|${f.time}" title="${f.time}s: ${f.value}">◆</button>`).join('')}</div></div>`).join('')}${selectedKey?`<div class="inline key-editor"><label>Time<input data-key-edit="time" type="number" step=".01" value="${selectedKey.time}"></label><label>Value<input data-key-edit="value" type="number" step=".01" value="${clip.tracks[selectedKey.parameter]?.find(f=>Math.abs(f.time-selectedKey.time)<1e-6)?.value??0}"></label><label>Easing<select data-key-edit="easing"><option>linear</option><option>easeIn</option><option>easeOut</option><option>easeInOut</option></select></label><button id="delete-key" class="danger">Delete key</button></div>`:''}`:'<p>Create an editable animation clip.</p>'}`;}
  function autoKey(parameter,value){const state=store.getState(),clip=active(state);if(!clip||!state.animationEditor.autoKey||!clip.tracks[parameter])return;mutate((d)=>upsertKeyframe(active(d),parameter,d.animationEditor.playhead,value));}
  host.addEventListener('change',(e)=>{if(e.target.id==='auto-key')mutate((d)=>{d.animationEditor.autoKey=e.target.checked;});});
  return {render,autoKey};
}
