/**
 * The mascot face (docs/MASCOT_DESIGN.md).
 *
 * One template, deliberately: three starter faces meant three sets of artwork
 * to keep rigged, and the two extra ones were strictly smaller than this. What
 * a beginner needs is a complete face they can strip down, not three partial
 * ones they have to build up.
 *
 * Every id here is wired by `applyTemplateProject`, so the two files are read
 * together. Paint order is the layer order: what is written first is behind.
 *
 * **Drawn for a rig, not for one illustration.** Every outline is generated by
 * a function of the pose rather than typed out once, which is what lets a
 * three-quarter view be a *shape key* on the same path instead of a second
 * drawing: same commands, same order, same count, so a delta exists between
 * any two of them (docs/SHAPE_KEYS.md). The turn the design brief asked for —
 * "les formes ne tournent pas réellement" — is that, and only that.
 *
 * The eyes are clipped to their socket. That is what lets a pupil sit *behind*
 * the eyelid rather than fading out as the eye closes — the lid is an ordinary
 * skin-coloured shape parked above the eye, and everything outside the socket
 * is simply not drawn.
 *
 * The fringe is clipped the same way, to the head itself. It is drawn well
 * inside the silhouette on both sides: whatever the turn or the hair movement
 * does to it, it can neither leave the outline nor uncover the hairline.
 */
const SKIN = '#f6d6ad', LINE = '#8f5c3c', HAIR = '#6b4430', HAIR_TOP = '#7d5238', HAIR_BACK = '#4e2f22';
const SHADE = '#c98d5e', NOSE = '#f0c79c', LIP = '#a8404b', MOUTH = '#5e1f27', TONGUE = '#c9566e', TEETH = '#fffdf7', DARK = '#263238';

/**
 * Stroke weights, as a hierarchy rather than as eight independent numbers.
 *
 * The old face had the head at 4 and the eyebrows at 8, so the strongest line
 * in the drawing was an eyebrow and the silhouette was the weakest thing in
 * it. A mascot is read as a silhouette first (docs/MASCOT_DESIGN.md §2), so
 * the outline is now the heaviest line and everything drawn *on* the face is
 * lighter than it, in one descending order.
 */
const STROKE = Object.freeze({ head: 6.5, brow: 5, mouth: 5, ear: 4.5, eye: 3.4, nose: 2.8, lid: 2.6, detail: 2.4 });

/** One decimal is plenty for a 240-unit artboard, and keeps the paths short. */
const round = (value) => Math.round(value * 10) / 10;
const point = (p) => `${round(p.x)} ${round(p.y)}`;
const clamp = (value, min, max) => Math.max(min, Math.min(max, Number(value) || 0));

/**
 * A smooth curve through a list of points, as cubics.
 *
 * Catmull-Rom, converted segment by segment: the curve passes *through* every
 * point, so a shape is authored by moving points rather than by guessing at
 * handles — and, far more importantly here, the command list depends only on
 * how many points there are. Two poses of the same shape therefore always
 * match structurally, which is the one thing a shape key requires.
 */
const cubic = (p0, p1, p2, p3) => `C${point({ x: p1.x + (p2.x - p0.x) / 6, y: p1.y + (p2.y - p0.y) / 6 })}`
  + ` ${point({ x: p2.x - (p3.x - p1.x) / 6, y: p2.y - (p3.y - p1.y) / 6 })} ${point(p2)}`;

/** A closed ring: every point is a knot, and the curve comes back round. */
function closedCurve(points) {
  const n = points.length;
  const at = (index) => points[(index + n) % n];
  const parts = [`M${point(points[0])}`];
  for (let i = 0; i < n; i += 1) parts.push(cubic(at(i - 1), at(i), at(i + 1), at(i + 2)));
  return `${parts.join(' ')} Z`;
}

/** The same, open: the ends duplicate their neighbour, so the curve stops flat. */
function openCurve(points) {
  const n = points.length;
  const at = (index) => points[Math.max(0, Math.min(n - 1, index))];
  const parts = [];
  for (let i = 0; i < n - 1; i += 1) parts.push(cubic(at(i - 1), at(i), at(i + 1), at(i + 2)));
  return parts.join(' ');
}

/* ── The head ─────────────────────────────────────────────────────────────
 *
 * Not a circle. A circle compressed horizontally is an ellipse, never a turned
 * head, and that single fact was most of what read as "the features slide over
 * a disc": there was no silhouette carrying any information about which way
 * the face pointed (docs/MASCOT_DESIGN.md §1).
 *
 * So the outline is a *profile*: a broad cranium, cheekbones, a jaw that draws
 * in, and a soft chin. Half of it is written down and the other half is its
 * mirror, which is what guarantees a symmetric rest pose to the last decimal.
 */
export const HEAD = Object.freeze({ cx: 120, cy: 120, rx: 100, ry: 104 });

/**
 * The right half of the head, crown to chin, and what a turn does to it.
 *
 * `far` is the displacement this anchor takes when it is on the half turning
 * *away* from the viewer, `near` when it is on the half coming towards them —
 * both written in the right-hand frame and mirrored for the left, so turning
 * left is exactly turning right reflected, by construction rather than by
 * tuning.
 *
 * The numbers say what a three-quarter view actually does: the cranium's
 * widest points barely move (a skull is nearly round in plan, and its
 * silhouette survives a turn), while the cheek, the jaw and the chin swing a
 * long way. That is why the outline can carry the turn without the head
 * appearing to shrink — the *shape* changes, the width does not.
 */
const HEAD_PROFILE = Object.freeze([
  Object.freeze({ x: 0, y: -104, mid: Object.freeze({ dx: -4, dy: 0 }) }),                                              // crown
  Object.freeze({ x: 58, y: -92, far: Object.freeze({ dx: -10, dy: -2 }), near: Object.freeze({ dx: 6, dy: 1 }) }),     // temple
  Object.freeze({ x: 100, y: -34, far: Object.freeze({ dx: -1, dy: -2 }), near: Object.freeze({ dx: 1, dy: 1 }) }),     // widest
  Object.freeze({ x: 88, y: 22, far: Object.freeze({ dx: -14, dy: -2 }), near: Object.freeze({ dx: 2, dy: 1 }) }),      // cheekbone
  Object.freeze({ x: 68, y: 68, far: Object.freeze({ dx: -14, dy: -6 }), near: Object.freeze({ dx: 4, dy: 2 }) }),      // jaw
  Object.freeze({ x: 34, y: 94, far: Object.freeze({ dx: -13, dy: -5 }), near: Object.freeze({ dx: -10, dy: 1 }) }),    // chin corner
  Object.freeze({ x: 0, y: 100, mid: Object.freeze({ dx: 14, dy: -2 }) })                                               // chin
]);

/**
 * One anchor, on one side, at one turn.
 *
 * `side` is +1 for the written half and −1 for its mirror. An anchor is "away"
 * when its side and the turn have the same sign, which is the whole of the
 * near/far bookkeeping: at `turn = +1` the face points to the right of the
 * screen, so the right-hand half is the one going away.
 */
function anchorAt(anchor, side, turn) {
  const amount = Math.abs(turn);
  if (anchor.mid) return { x: anchor.mid.dx * turn, y: anchor.y + anchor.mid.dy * amount };
  const shift = side * turn > 0 ? anchor.far : anchor.near;
  return { x: side * (anchor.x + shift.dx * amount), y: anchor.y + shift.dy * amount };
}

/**
 * The furthest any knot is drawn inwards on the half turning away.
 *
 * Anything drawn on the face that does *not* follow the turned outline has to
 * stay at least this far inside it, or it hangs outside the head at a full
 * turn. The cheek shading is the one such thing (`SHADE_INSET`).
 */
export const HEAD_FAR_PULL = Math.max(...HEAD_PROFILE.map((anchor) => (anchor.far ? -anchor.far.dx : 0)));

/** The whole outline as twelve knots, clockwise from the crown, in head-local units. */
export function headRing(turn = 0) {
  const t = clamp(turn, -1, 1);
  const ring = HEAD_PROFILE.map((anchor) => anchorAt(anchor, 1, t));
  for (let i = HEAD_PROFILE.length - 2; i >= 1; i -= 1) ring.push(anchorAt(HEAD_PROFILE[i], -1, t));
  return ring;
}

/** Head-local → artboard, with the jaw stretch applied on the way. */
const placed = (p, grow) => ({ x: HEAD.cx + p.x, y: HEAD.cy + (p.y > 0 ? p.y * grow : p.y) });

/** A point pushed out of the head, along the radius: how hair sits on a skull. */
function outward(p, amount) {
  const nx = p.x / HEAD.rx, ny = p.y / HEAD.ry;
  const length = Math.hypot(nx, ny) || 1;
  return { x: p.x + (nx / length) * amount, y: p.y + (ny / length) * amount };
}

/**
 * The head, as one outline that turns and lengthens.
 *
 * It used to be a circle with a wider ellipse hidden behind it, and dropping
 * that ellipse gave the mascot a **double chin**: two arcs crossing at the
 * jaw, because two outlines cannot be one silhouette however carefully they
 * are placed.
 *
 * So there is one outline, and both the jaw and the turn are shape keys on it.
 * `jaw` stretches everything below the middle line downwards, which is what a
 * jaw opening looks like from the front; `turn` swings the profile, which is
 * what a head does when it looks somewhere.
 */
export function headPath({ jaw = 0, turn = 0 } = {}) {
  const grow = 1 + clamp(jaw, 0, 2) * 0.16;
  return closedCurve(headRing(turn).map((p) => placed(p, grow)));
}

export const HEAD_REST = headPath();

/** The clip the fringe lives in: the head, with a little room for the stroke. */
const HEAD_CLIP = closedCurve(headRing(0).map((p) => placed(outward(p, 3), 1)));

/* ── Hair ─────────────────────────────────────────────────────────────────
 *
 * Three masses, three tones, and all of them built from the head's own knots,
 * so the hair is a skull with hair on it rather than a shape that happens to
 * sit near one. That is what makes the crown follow a turn for free: ask for
 * the turned ring and the cap comes back turned.
 */
const RING = Object.freeze({ crown: 0, temple: 1, widest: 2, cheek: 3, jaw: 4 });
const mirrorIndex = (index) => (index === 0 ? 0 : 12 - index);

/** The knots of the cap: the widest point up over the crown and down the other side. */
const capIndices = [RING.widest, RING.temple, RING.crown, mirrorIndex(RING.temple), mirrorIndex(RING.widest)];

/**
 * The hairline, and what a turn does to it.
 *
 * Off-centre on purpose (docs/MASCOT_DESIGN.md §4.6): a parting a third of the
 * way across is the cheapest asymmetry there is, and asymmetry is what stops a
 * three-quarter view reading as a squashed front view. Written left to right,
 * because the cap walks its outer edge right to left and comes back along this.
 */
const HAIRLINE = Object.freeze([
  Object.freeze({ x: -98, y: -22 }), Object.freeze({ x: -76, y: -52 }), Object.freeze({ x: -42, y: -70 }),
  Object.freeze({ x: -8, y: -50 }), Object.freeze({ x: 32, y: -74 }), Object.freeze({ x: 72, y: -52 }),
  Object.freeze({ x: 98, y: -22 })
]);

/**
 * A point of the hairline under a turn.
 *
 * The outer edge gets the head's own knots, so it is exact; the hairline is
 * interior and gets the same story told analytically — it follows the crown
 * backwards, and the half going away draws in while the half coming forward
 * eases out. Close enough to the outline's own numbers that the cap keeps its
 * thickness, which is all it has to do.
 */
function hairlineAt(p, turn) {
  const amount = Math.abs(turn);
  const u = clamp(p.x / HEAD.rx, -1, 1);
  const away = p.x * turn > 0;
  return { x: p.x - 6 * turn * (1 - Math.abs(u)) + (away ? -0.1 : 0.05) * p.x * amount, y: p.y };
}

/** The cap: the hair that is part of the silhouette, so it turns with it. */
export function hairTopPath({ turn = 0 } = {}) {
  const ring = headRing(turn);
  const outer = capIndices.map((index) => placed(outward(ring[index], 6), 1));
  const inner = HAIRLINE.map((p) => placed(hairlineAt(p, clamp(turn, -1, 1)), 1));
  return `M${point(outer[0])} ${openCurve(outer)} L${point(inner[0])} ${openCurve(inner)} Z`;
}

/**
 * The mass behind the head.
 *
 * Deliberately fuller on one side, and deliberately *not* given a turned
 * outline of its own: it is behind the skull, so what it has to do on a turn
 * is swing the other way from the face — which the rig gives it for free by
 * authoring it at a negative depth (docs/MASCOT_DESIGN.md §5). The back of a
 * head going one way while the nose goes the other is most of what reads as
 * rotation.
 */
export function hairBackPath() {
  const ring = headRing(0);
  const indices = [RING.cheek, RING.widest, RING.temple, RING.crown,
    mirrorIndex(RING.temple), mirrorIndex(RING.widest), mirrorIndex(RING.cheek)];
  // Thin over the crown: the artboard's top edge is four units above the skull,
  // and a mascot may not be cropped by its own hair.
  const thickness = (index) => (index === RING.crown ? 8 : (ring[index].x > 0 ? 7 : 14));
  const outer = indices.map((index) => placed(outward(ring[index], thickness(index)), 1));
  const inner = [...indices].reverse().map((index) => placed(outward(ring[index], 2), 1));
  return `M${point(outer[0])} ${openCurve(outer)} L${point(inner[0])} ${openCurve(inner)} Z`;
}

/**
 * The fringe: locks hanging off the hairline, clipped to the head.
 *
 * Drawn well inside the silhouette on both sides, which is what lets it skip a
 * turned outline of its own: measured on the real curves, the worst clearance
 * at a full turn either way is about seven units, and the head clip is behind
 * that as a second line of defence.
 */
export function hairPath() {
  return closedCurve([
    // Tucked under the cap: every point of this edge sits above the hairline.
    { x: -92, y: -34 }, { x: -74, y: -58 }, { x: -42, y: -74 }, { x: -8, y: -56 }, { x: 32, y: -78 },
    { x: 70, y: -58 }, { x: 92, y: -34 },
    // and the locks, right to left, well inside the silhouette on both sides.
    { x: 80, y: -36 }, { x: 52, y: -58 }, { x: 26, y: -44 }, { x: -6, y: -62 }, { x: -34, y: -42 },
    { x: -68, y: -56 }
  ].map((p) => placed(p, 1)));
}

/* ── Eyes ─────────────────────────────────────────────────────────────────
 *
 * Almonds, not ellipses, and each one the mirror of the other rather than the
 * same drawing twice (docs/MASCOT_DESIGN.md §4.2). Two identical ellipses read
 * as two discs stuck on a face however far the rig displaces them, because a
 * disc looks the same from every angle; an almond has a near corner and a far
 * corner, so foreshortening it actually shows.
 */
export const EYE = Object.freeze({ left: { cx: 82, cy: 118 }, right: { cx: 158, cy: 118 } });

/** Written outer-corner first, in the frame of the *right* eye; the left mirrors it. */
const EYE_PROFILE = Object.freeze([
  Object.freeze({ x: 29, y: -5 }), Object.freeze({ x: 12, y: -21 }), Object.freeze({ x: -12, y: -18 }),
  Object.freeze({ x: -28, y: 3 }), Object.freeze({ x: -12, y: 17 }), Object.freeze({ x: 13, y: 19 })
]);

/** One eye, at a size: the socket asks for a slightly larger one than the white. */
export function eyePath(side, { scale = 1 } = {}) {
  const { cx, cy } = side === 'Right' ? EYE.right : EYE.left;
  const flip = side === 'Right' ? 1 : -1;
  return closedCurve(EYE_PROFILE.map((p) => ({ x: cx + p.x * flip * scale, y: cy + p.y * scale })));
}

/* ── Ears ─────────────────────────────────────────────────────────────────
 *
 * Simple and rounded, with one fold, sitting at the cheekbone where a skull
 * actually carries them. What makes them read on a turn is the rig, not the
 * drawing: the near one widens and comes forward, the far one narrows, fades
 * and is repainted *behind* the head (3D-08).
 */
export const EAR = Object.freeze({ left: { cx: 23, cy: 124 }, right: { cx: 217, cy: 124 } });

const EAR_PROFILE = Object.freeze([
  Object.freeze({ x: -6, y: -27 }), Object.freeze({ x: 12, y: -20 }), Object.freeze({ x: 18, y: 2 }),
  Object.freeze({ x: 9, y: 24 }), Object.freeze({ x: -6, y: 27 }), Object.freeze({ x: -12, y: 0 })
]);

export function earPath(side) {
  const { cx, cy } = side === 'Right' ? EAR.right : EAR.left;
  const flip = side === 'Right' ? 1 : -1;
  return closedCurve(EAR_PROFILE.map((p) => ({ x: cx + p.x * flip, y: cy + p.y })));
}

export function earFoldPath(side) {
  const { cx, cy } = side === 'Right' ? EAR.right : EAR.left;
  const flip = side === 'Right' ? 1 : -1;
  const at = (x, y) => point({ x: cx + x * flip, y: cy + y });
  return `M${at(6, -14)} Q${at(-2, 0)} ${at(4, 15)}`;
}

/* ── The nose ─────────────────────────────────────────────────────────────
 *
 * The old nose was a single stroked curve, which is the least a nose can be
 * and far too little to carry a turn: the head rotated and the one landmark
 * that should have said so kept its shape. This one is a closed, filled wedge
 * — still minimal, but it has a bridge, a ridge, two wings and a tip, and each
 * of them moves differently when the head turns (docs/MASCOT_DESIGN.md §4.3).
 *
 * At a three-quarter view the bridge lags behind (it is the least protruding
 * part of the nose, so it swings least), the wing coming towards the viewer
 * flares out and the one going away tucks in behind the ridge. That is the
 * whole of the yaw cue, and it is a shape rather than a slide.
 */
export const NOSE_AT = Object.freeze({ x: 120, y: 148 });

const NOSE_PROFILE = Object.freeze([
  Object.freeze({ x: 0, y: -15, mid: Object.freeze({ dx: -7, dy: 0 }) }),                                             // bridge
  Object.freeze({ x: 8, y: -7, far: Object.freeze({ dx: -5, dy: -1 }), near: Object.freeze({ dx: 2, dy: 0 }) }),     // ridge
  Object.freeze({ x: 16, y: 6, far: Object.freeze({ dx: -9, dy: -1 }), near: Object.freeze({ dx: 3, dy: 0 }) }),      // wing
  Object.freeze({ x: 11, y: 14, far: Object.freeze({ dx: -7, dy: -1 }), near: Object.freeze({ dx: 5, dy: 1 }) }),     // nostril
  Object.freeze({ x: 0, y: 16, mid: Object.freeze({ dx: 5, dy: 0 }) })                                                // tip
]);

export function nosePath({ turn = 0 } = {}) {
  const t = clamp(turn, -1, 1);
  const ring = NOSE_PROFILE.map((anchor) => anchorAt(anchor, 1, t));
  for (let i = NOSE_PROFILE.length - 2; i >= 1; i -= 1) ring.push(anchorAt(NOSE_PROFILE[i], -1, t));
  return closedCurve(ring.map((p) => ({ x: NOSE_AT.x + p.x, y: NOSE_AT.y + p.y })));
}

export const NOSE_REST = nosePath();

/* ── Eyebrows ─────────────────────────────────────────────────────────────*/

export function browPath(side) {
  const flip = side === 'Right' ? 1 : -1;
  const { cx } = side === 'Right' ? EYE.right : EYE.left;
  const at = (x, y) => point({ x: cx + x * flip, y: 82 + y });
  return `M${at(-26, 5)} Q${at(0, -13)} ${at(26, 4)}`;
}

/* ── The mouth ────────────────────────────────────────────────────────────
 *
 * One closed shape, which is the one thing about the old face that was right
 * and is kept.
 *
 * It used to be two: a stroked lip line that morphed for the smile, and a
 * filled cavity that scaled for the opening. Two shapes deforming under two
 * different systems cannot agree — a smile put the lip corners outside the
 * cavity, and half-open the lip sat across the hole like a stick. One closed
 * path has no such seam: the fill *is* the inside of the mouth and the stroke
 * *is* the lips, so every pose is a mouth.
 *
 * Every control point is affine in `open`, `smile` and `turn`, which is what
 * lets three additive shape keys reproduce any combination exactly rather than
 * approximately (docs/SHAPE_KEYS.md).
 */

/**
 * Where the mouth's four control points are for one pose.
 *
 * `turn` is the asymmetry a three-quarter view needs and a translation cannot
 * give: the corner going away draws in towards the middle while the near one
 * stays out, and the middle of the lip line — the philtrum, which follows the
 * nose — travels further than either corner. The corners move together, so the
 * mouth's *width* is left to the rig's own foreshortening and this is purely
 * the shape.
 */
export function mouthGeometry({ open = 0, smile = 0, turn = 0 } = {}) {
  const t = clamp(turn, -1, 1);
  const cornerY = 172 - 8 * smile;
  const slide = -2 * t;
  return {
    left: { x: 88 + slide, y: cornerY },
    right: { x: 152 + slide, y: cornerY },
    top: { x: 120 + 7 * t, y: 168 + 11 * smile },
    bottom: { x: 120 + 7 * t, y: 179 + 11 * smile + 42 * open }
  };
}

/** A point on a quadratic, so what goes inside the mouth can sit on its own lips. */
const quad = (p0, c, p2, t) => {
  const u = 1 - t;
  return { x: u * u * p0.x + 2 * u * t * c.x + t * t * p2.x, y: u * u * p0.y + 2 * u * t * c.y + t * t * p2.y };
};
/** The control point of the quadratic through three points, which is how a band follows a lip. */
const through = (a, mid, b) => ({ x: 2 * mid.x - (a.x + b.x) / 2, y: 2 * mid.y - (a.y + b.y) / 2 });

export function mouthPath(pose = {}) {
  const g = mouthGeometry(pose);
  return `M${point(g.left)} Q${point(g.top)} ${point(g.right)} Q${point(g.bottom)} ${point(g.left)} Z`;
}

/**
 * Teeth and tongue.
 *
 * Both are drawn *from the mouth's own curves* rather than beside them: the
 * teeth hang off the upper lip, the tongue sits on the lower one. Inside by
 * construction, which is the whole reason the cavity used to come apart — a
 * shape that only happens to line up stops lining up the moment anything
 * moves. `turn` reaches them through the same geometry, so a turned mouth
 * takes what is behind it with it instead of leaving it floating.
 *
 * `show` is how far they come out, and at 0 the shape is a flat line with no
 * height at all: closed lips have nothing behind them to hide.
 */
const BAND = Object.freeze({ from: 0.2, to: 0.8, teeth: 0.3, tongue: 0.52 });

const mouthDepth = (g) => (g.bottom.y - g.top.y) / 2;

export function teethPath({ open = 0, smile = 0, turn = 0, show = 0 } = {}) {
  const g = mouthGeometry({ open, smile, turn });
  const lip = (t) => quad(g.left, g.top, g.right, t);
  const a = lip(BAND.from), b = lip(BAND.to), control = through(a, lip(0.5), b);
  const drop = mouthDepth(g) * BAND.teeth * show;
  const down = (p) => ({ x: p.x, y: p.y + drop });
  return `M${point(a)} Q${point(control)} ${point(b)} L${point(down(b))} Q${point(down(control))} ${point(down(a))} Z`;
}

export function tonguePath({ open = 0, smile = 0, turn = 0, show = 0 } = {}) {
  const g = mouthGeometry({ open, smile, turn });
  // The lower lip, walked right to left, so the tongue is wound the same way
  // round as the teeth and the two shapes stay comparable.
  const lip = (t) => quad(g.right, g.bottom, g.left, t);
  const a = lip(BAND.from), b = lip(BAND.to), control = through(a, lip(0.5), b);
  const rise = mouthDepth(g) * BAND.tongue * show;
  const up = (p) => ({ x: p.x, y: p.y - rise });
  return `M${point(a)} Q${point(control)} ${point(b)} L${point(up(b))} Q${point(up(control))} ${point(up(a))} Z`;
}

export const MOUTH_REST = mouthPath();
export const TEETH_REST = teethPath();
export const TONGUE_REST = tonguePath();

/* ── Light ────────────────────────────────────────────────────────────────
 *
 * A crescent down the cheek, and nothing else.
 *
 * The old face carried two half-opaque slabs from temple to jaw, and they were
 * doing the volume's job: take them away and the head was a flat disc again.
 * The rule now is the one the brief states — the drawing has to read without
 * them (docs/MASCOT_DESIGN.md §1) — so what is left is narrow, soft and
 * roughly a third of the opacity it was. It supports the turn; it no longer
 * has to invent it.
 */
export const SHADE_INSET = 17;

export function shadePath(side) {
  const flip = side === 'Right' ? 1 : -1;
  const ring = headRing(0);
  const edge = (index, inset) => placed(outward(ring[index], -inset), 1);
  const at = (p) => ({ x: HEAD.cx + (p.x - HEAD.cx) * flip, y: p.y });
  // A lens that tapers to nothing at both ends, and set a clear `SHADE_INSET`
  // inside the outline. Both matter. The taper is what makes a flat fill read
  // as light rather than as a stripe; the inset is what keeps it inside the
  // *turned* silhouette, which the shading itself does not follow — the far
  // cheek comes in by fourteen units at a full turn, and a band drawn on the
  // edge would hang outside the face there.
  const outer = [edge(RING.widest, SHADE_INSET), edge(RING.cheek, SHADE_INSET), edge(RING.jaw, SHADE_INSET)].map(at);
  const inner = [edge(RING.jaw, SHADE_INSET), edge(RING.cheek, 36), edge(RING.widest, SHADE_INSET)].map(at);
  return `M${point(outer[0])} ${openCurve(outer)} L${point(inner[0])} ${openCurve(inner)} Z`;
}

/* ── The document ─────────────────────────────────────────────────────────*/

/**
 * Left and right are the viewer's, which is how an author points at them.
 *
 * The clip is on the eye group itself, not on a wrapper inside it, so it
 * travels with the eye: the 2.5D turn moves the whole assembly -- socket,
 * white, pupil, lids and outline -- as one, instead of sliding the contents out
 * from under a socket pinned to the face. Everything the lids push past the
 * socket edge is simply not drawn.
 */
const eye = (side) => {
  const { cx, cy } = side === 'Right' ? EYE.right : EYE.left;
  const shape = eyePath(side);
  const inner = side === 'Right' ? -1 : 1;
  return `<g id="eye${side}" data-name="${side} eye" clip-path="url(#eyeSocket${side})">
      <path id="eyeWhite${side}" data-name="${side} eye white" d="${shape}" fill="#ffffff" />
      <circle id="pupil${side}" data-name="${side} pupil" cx="${cx}" cy="${cy}" r="10.5" fill="${DARK}" />
      <circle id="glint${side}" data-name="${side} eye glint" cx="${cx + inner * 4}" cy="${cy - 6}" r="3.6" fill="#ffffff" opacity=".9" />
      <path id="lidUpper${side}" data-name="${side} upper eyelid" d="M${cx - 48} 68 h96 v52 q-48 13 -96 0 Z" fill="${SKIN}" stroke="${LINE}" stroke-width="${STROKE.lid}" />
      <path id="lidLower${side}" data-name="${side} lower eyelid" d="M${cx - 48} 168 h96 v-48 q-48 -11 -96 0 Z" fill="${SKIN}" stroke="${LINE}" stroke-width="${STROKE.detail}" />
      <path id="rim${side}" data-name="${side} eye outline" d="${shape}" fill="none" stroke="${LINE}" stroke-width="${STROKE.eye}" />
    </g>`;
};

const ear = (side) => `<g id="ear${side}" data-name="${side} ear"><path id="ear${side}Shape" data-name="${side} ear shape" d="${earPath(side)}" fill="${SKIN}" stroke="${LINE}" stroke-width="${STROKE.ear}" stroke-linejoin="round" /><path id="ear${side}Fold" data-name="${side} ear fold" d="${earFoldPath(side)}" fill="none" stroke="${LINE}" stroke-width="${STROKE.detail}" stroke-linecap="round" opacity=".7" /></g>`;

export const MASCOT_FACE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240" role="img" aria-label="Cartoon mascot face">
  <defs>
    <clipPath id="eyeSocketLeft"><path d="${eyePath('Left', { scale: 1.12 })}" /></clipPath>
    <clipPath id="eyeSocketRight"><path d="${eyePath('Right', { scale: 1.12 })}" /></clipPath>
    <clipPath id="headShape"><path d="${HEAD_CLIP}" /></clipPath>
  </defs>
  <g id="faceRoot" data-name="Face">
    <path id="hairBack" data-name="Hair back" d="${hairBackPath()}" fill="${HAIR_BACK}" />
    ${ear('Left')}
    ${ear('Right')}
    <path id="head" data-name="Head shape" d="${HEAD_REST}" fill="${SKIN}" stroke="${LINE}" stroke-width="${STROKE.head}" stroke-linejoin="round" />
    <path id="shadeLeft" data-name="Left cheek shade" d="${shadePath('Left')}" fill="${SHADE}" opacity=".22" />
    <path id="shadeRight" data-name="Right cheek shade" d="${shadePath('Right')}" fill="${SHADE}" opacity=".22" />
    <path id="mouth" data-name="Mouth" d="${MOUTH_REST}" fill="${MOUTH}" stroke="${LIP}" stroke-width="${STROKE.mouth}" stroke-linejoin="round" />
    <path id="tongue" data-name="Tongue" d="${TONGUE_REST}" fill="${TONGUE}" />
    <path id="teeth" data-name="Teeth" d="${TEETH_REST}" fill="${TEETH}" />
    <path id="nose" data-name="Nose" d="${NOSE_REST}" fill="${NOSE}" stroke="${LINE}" stroke-width="${STROKE.nose}" stroke-linejoin="round" />
    ${eye('Left')}
    ${eye('Right')}
    <g id="eyebrows" data-name="Eyebrows" fill="none" stroke="#57382b" stroke-width="${STROKE.brow}" stroke-linecap="round">
      <path id="browLeft" data-name="Left eyebrow" d="${browPath('Left')}" />
      <path id="browRight" data-name="Right eyebrow" d="${browPath('Right')}" />
    </g>
    <path id="hairTop" data-name="Hair top" d="${hairTopPath()}" fill="${HAIR_TOP}" />
    <g id="hairFront" data-name="Hair front" clip-path="url(#headShape)"><path id="hair" data-name="Fringe" d="${hairPath()}" fill="${HAIR}" /></g>
  </g>
</svg>`;
